parameters:
#    hitkari_demo.example.class: Hitkari\DemoBundle\Example

services:
#    hitkari_demo.example:
#        class: %hitkari_demo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
